### ISSUE TITLE
Unable to provide configuration.toml via device-config interface

### ISSUE THREAD

**Issue by farshidtz** [canonical/edgex-config-provider#2]
The `device-config` plugs of device snaps set their target paths to the `res` directory which is expected to contain the configuration files and directories.

For example, see https://github.com/edgexfoundry/device-mqtt-go/blob/v2.1.0/snap/snapcraft.yaml#L52
```yaml
plugs:
  device-config:
    interface: content
    content: device-config
    target: $SNAP_DATA/config/device-mqtt/res
```

Snapd allows a provider to mount directories beneath the target path set by the consumer. Read more: https://snapcraft.io/docs/content-interface

Given that the `device-config` sets it target to `$SNAP_DATA/config/device-mqtt/res`, the provider would be allowed to bind mounting directories inside of it. This makes it impossible (without additional hooks on the consumer side) to provide the `configuration.toml` file at `$SNAP_DATA/config/device-mqtt/res/configuration.toml`. 

In order for this to work and allow providing the all files and directories (e.g. `configuration.toml`, `devices`, `profiles`) under the `res` directory, the `device-config` plug need to expose the parent directory on target. That way the provider can pack all files and directories inside a `res` directory and bind mount it inside the target path of the consumer.

The example above would need to change to:
```yaml
plugs:
  device-config:
    interface: content
    content: device-config
    target: $SNAP_DATA/config/device-mqtt
```

---
Fix checklist:

- [x] https://github.com/edgexfoundry/device-modbus-go/pull/302
- [x] https://github.com/edgexfoundry/device-snmp-go/pull/131
- [x] https://github.com/edgexfoundry/device-rest-go/pull/148
- [x] https://github.com/edgexfoundry/device-mqtt-go/pull/327 
- [x] https://github.com/edgexfoundry/device-camera-go/pull/165
